<form action="<?php if(is_null($id)):?>addcategorie.php<?php else:?>editcategorie.php<?php endif;?>" method="POST" enctype="multipart/form-data" class="text-center m-auto">
    
    <?php if(isset($errorForm) && count($errorForm) > 0):?>
        <?php foreach($errorForm as $error):?>
            <div class="alert alert-danger" role="alert">
                <ul>
                    <li><?=$error?></li>
                </ul>
            </div>
         <?php endforeach;?>
    <?php endif;?>
    
    
    <?php if(!is_null($id)):?>
        <input type="hidden" value="<?=$id?>" name="id">
    <?php endif;?>
    
    <fieldset>
        
        <div class="form-group ">
            <div class="row d-flex flex-row justify-content-center">
                <div class="col-4 ">
                    <label for="titlecategorie">Titre de la catégorie</label>
                    <input type="text" class="form-control rounded" id="titlecategorie" name="titlecategorie" value="<?=$titrecategorie?>">
                    <small id="titleHelp" class="form-text text-muted">Saisissez un titre pour votre catégorie</small>
                </div>
            </div>
        </div>
        
   
        <div class="form-group">
             <div class="row d-flex flex-row justify-content-center">
                <div class="col-4 ">
                    <label for="parentcategorie">Parent:</label> <br>
                    <select class="form-control rounded" name="parentcategorie" id="parentcategorie" value="<?=$parentcategorie?>">
                     
                        <?php foreach($categories as $categorie):?>
                            <option value="<?=$categorie['c_id']?>"><?=$categorie['c_parent']?></option>
                        <?php endforeach;?>

                    </select>
                    <small id="catHelp" class="form-text text-muted">Sélectionnez le parent de la catégorie</small>
                </div>
            </div>
        </div>
        
         
        
        <button type="submit" name=" submit" class="btn btn-primary rounded px-5 py-3">Créer l'article</button>
    </fieldset>
</form>


<script src="https://cloud.tinymce.com/5/tinymce.min.js"></script>
<script type="text/javascript">
    $(function () {
        
        tinymce.init({ selector:'textarea' });
      
     
    });
