<!doctype html>
<html lang="fr">   <!-- vrai lang "fr" -->       
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width-device-width, initial-scale=1.0, user-scalable-yes"> 
		<meta name="description" content="" />
		<meta http-equiv="X-UA-Compatible" content="ie-edge">
		<title> Blog-Back Office </title>
<!--police -->

<!--biblio icones -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<!-- css -->
       
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/datatables.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/picto.css">
    
<!-- js boostrap -->   
    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
     <script src="js/datatables.min.js"></script>
     <script src="js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />
    
    </head>
    <body>
      <header>
        <div class="container-fluid text-center">
          <p class="degrade">Le blog de Morgane - Back Office</p>
          <img src="img/licorne.jpg" >
        </div>
            
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="index.php">Admin Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item <?php if($menuSelected == 'home'):?>active<?php endif;?>">
                        <a class="nav-link" href="index.php">Accueil <?php if($menuSelected == 'home'):?><span class="sr-only">(current)</span><?php endif;?></a>
                    </li>
                    <li class="nav-item dropdown <?php if($menuSelected == 'addArticle' || $menuSelected == 'listeArticle' || $menuSelected == 'editArticle'):?>active<?php endif;?>">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarArticle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Articles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarArticle">
                            <a class="dropdown-item <?php if($menuSelected == 'listeArticle'):?>active<?php endif;?>" href="listearticle.php">Liste</a>
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item  <?php if($menuSelected == 'addArticle'):?>active<?php endif;?>" href="addarticle.php">Ajouter</a>
                        </div>
                    </li>
                    
                    <li class="nav-item dropdown <?php if($menuSelected == 'addCategorie' || $menuSelected == 'listeCategorie' || $menuSelected == 'editCategorie'):?>active<?php endif;?>">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarArticle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Articles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarArticle">
                            <a class="dropdown-item <?php if($menuSelected == 'listeCategorie'):?>active<?php endif;?>" href="listecategorie.php">Liste</a>
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item  <?php if($menuSelected == 'addCategorie'):?>active<?php endif;?>" href="addcategorie.php">Ajouter</a>
                        </div>
                    </li>
                    
                    
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#">Commentaires</a>
                    </li>
                    <li class="nav-item dropdown <?php if($menuSelected == 'addUser' || $menuSelected == 'listeUser' || $menuSelected == 'editUser'):?>active<?php endif;?>">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Utilisateurs
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarUser">
                            <a class="dropdown-item <?php if($menuSelected == 'listeUser'):?>active<?php endif;?>" href="listeuser.php">Liste</a>
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item  <?php if($menuSelected == 'addUser'):?>active<?php endif;?>" href="adduser.php">Ajouter</a>
                        </div>
                    </li>
                </ul>
                
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
            
            
        </header>
        
        <main>
            
            <div class="container mb-4">
       
                <?php if(isset($flashbag) && $flashbag!=false):?>
                    <div class="alert alert-success" role="alert">
                        <?php foreach($flashbag as $message):?>
                            <?=$message?>
                        <?php endforeach;?>
                    </div>
                <?php endif;?> 
                
            
            
                <?php
                    include('tpl/'.$vue);
                ?>     
            </div>
            
            
            <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Suppression</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            Êtes-vous sûr de vouloir supprimer cet element ?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a id="linkdelete" href="test.php"><button type="button" class="btn btn-primary">Supprimer</button></a>
                        </div>
                    </div>
                </div>
            </div>
            
        </main>
        
        <footer>
            
        </footer>
        
        <script src="js/jquery-3.3.1.min.js"></script>
        <script src="js/bootstrap.bundle.min.js"></script>
        <script src="js/datatables.min.js"></script>
        <script src="js/jquery.dataTables.min.js"></script>
        
        <script>
        
        
        
        
            //DataTable
            $(document).ready( function () {
            $('#tableDonnee').DataTable({
                colReorder: true,
                stateSave: true,
                dom: 'Bfrtip',
                buttons: [
                    'pageLength',
                    'print',
                    'copyHtml5',
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5',
                    'colvis'
                ],
                columnDefs: [
                    { "orderable": false, "targets": 5 }
                ]
            });
        });
           // Modal delete Bootstrap
            $('#delete').on('show.bs.modal', function (e) {
              $('#linkdelete').attr("href", e.relatedTarget.href);
            });
        </script>
    </body>
</html>