<section>
    <p class="text-right"><a href="adduser.php" class="btn btn-primary"><i class="icon-user-plus"></i> Ajouter un utilisateur</a></p>
    <table id="tableDonnee" class="table">
        <thead>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Email</th>
            <th>Rôle</th>
            <th>Actif</th>
            <th>Action</th>
        </thead>
        <tbody>
            <?php foreach($users as $user):?>
                <tr>
                    <td><?=$user['u_firstname']?></td>
                    <td><?=$user['u_lastname']?></td>
                    <td><?=$user['u_email']?></td>
                    <td><?=$user['u_role']?></td>
                    <td><a href="publishuser.php?id=<?=$user['u_id']?>"><i class="big <?php if($user['u_valide']==true):?>green icon-toggle-right<?php else:?>red icon-toggle-left<?php endif;?>"></i></a></td>
                    <td><a href="edituser.php?id=<?=$user['u_id']?>"><i class="fa fa-edit"></i></a> <a href="deluser.php?id=<?=$user['u_id']?>" data-toggle="modal" data-target="#delete"><i class="fa fa-trash"></i></a></a></td>
                </tr> 
            <?php endforeach;?>
        </tbody>
    </table>
</section>