<!doctype html>
<html lang="zxx">   <!-- vrai lang "fr" -->       
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width-device-width, initial-scale=1.0, user-scalable-yes"> 
		<meta name="description" content="" />
		<meta http-equiv="X-UA-Compatible" content="ie-edge">
		<title> Blog </title>
		
<!--police -->

<!--biblio icones -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<!-- css et bootstrap-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="../css/style.css" rel="stylesheet" type="text/css">
    
    </head>
    <body>
        <header>
            <img src="" alt="">
            <nav class="navbar navbar-expand-lg navbar-dark static-top ">
                <div class="container">
                  <div class="d-flex  ">
                    <a class="navbar-brand" href="#">Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                      <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="index.php">Accueil
                            <span class="sr-only">(current)</span>
                          </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" id="photo" href="">?</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">?</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">?</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">?</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Contact</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
            </nav>
        </header>
        <main>
            
               
          
        </main>
        <footer></footer>
        <script src="js/jquery-3.3.1.min.js"></script>
        <script src="js/script.js"></script>
    </body>
</html>